// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OIT_Startup_API.Data;

#nullable disable

namespace OIT_Startup_API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250926181553_Modified Menu Title")]
    partial class ModifiedMenuTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1403),
                            Description = "Amministratori di sistema",
                            IsActive = true,
                            IsSystemGroup = true,
                            Name = "Administrators",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1405)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1407),
                            Description = "Utenti standard",
                            IsActive = true,
                            IsSystemGroup = true,
                            Name = "Users",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1407)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1408),
                            Description = "Manager con privilegi estesi",
                            IsActive = true,
                            IsSystemGroup = false,
                            Name = "Managers",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1408)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.GroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("GroupId", "PermissionId")
                        .IsUnique();

                    b.ToTable("GroupPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1624),
                            GroupId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1629),
                            GroupId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1630),
                            GroupId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 4,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1630),
                            GroupId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 5,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1630),
                            GroupId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 6,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1632),
                            GroupId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 7,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1632),
                            GroupId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 8,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1633),
                            GroupId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 9,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1633),
                            GroupId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 10,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1666),
                            GroupId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 11,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1667),
                            GroupId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 12,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1668),
                            GroupId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 13,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1668),
                            GroupId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 14,
                            GrantedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1669),
                            GroupId = 3,
                            PermissionId = 8
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1505),
                            IsActive = true,
                            Name = "Visualizza Menu",
                            Resource = "Menu",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1505)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Manage",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1509),
                            IsActive = true,
                            Name = "Gestisci Menu",
                            Resource = "Menu",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1510)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1511),
                            IsActive = true,
                            Name = "Visualizza Utenti",
                            Resource = "User",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1511)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Create",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1512),
                            IsActive = true,
                            Name = "Crea Utenti",
                            Resource = "User",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1512)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Update",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1513),
                            IsActive = true,
                            Name = "Modifica Utenti",
                            Resource = "User",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1514)
                        },
                        new
                        {
                            Id = 6,
                            Action = "Delete",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1516),
                            IsActive = true,
                            Name = "Elimina Utenti",
                            Resource = "User",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1516)
                        },
                        new
                        {
                            Id = 7,
                            Action = "Manage",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1517),
                            IsActive = true,
                            Name = "Gestisci Gruppi Sicurezza",
                            Resource = "Group",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1517)
                        },
                        new
                        {
                            Id = 8,
                            Action = "Read",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1518),
                            IsActive = true,
                            Name = "Visualizza Reports",
                            Resource = "Report",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1518)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Manage",
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1520),
                            IsActive = true,
                            Name = "Gestisci Sistema",
                            Resource = "System",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1520)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1727),
                            Email = "admin@oit.it",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$007pBGqjmpMkk25IEHbKrO9Utd59B18AKoi2XCT8EK38mmgqAl9D6",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1727),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1755),
                            GroupId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Menu.MenuGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Order");

                    b.ToTable("MenuGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1764),
                            IsActive = true,
                            Order = 1,
                            Title = "Menu",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1764)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1766),
                            IsActive = true,
                            Order = 2,
                            Title = "Dashboard",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1766)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1768),
                            IsActive = true,
                            Order = 3,
                            Title = "Gestione",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1768)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1769),
                            IsActive = true,
                            Order = 4,
                            Title = "Analisi",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1769)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1770),
                            IsActive = true,
                            Order = 5,
                            Title = "Sistema",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1770)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Menu.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MenuGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("QueryParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MenuGroupId");

                    b.HasIndex("Order");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1784),
                            Icon = "list",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/menu",
                            Title = "Tutte le voci di menu",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1785)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1787),
                            Icon = "check_circle",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 2,
                            QueryParams = "\"{\\u0022active\\u0022:true}\"",
                            Route = "/menu",
                            Title = "Voci di menu attive",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(1787)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2033),
                            Icon = "error",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 3,
                            QueryParams = "\"{\\u0022expired\\u0022:true}\"",
                            Route = "/menu",
                            Title = "Voci di menu scadute",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2033)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2046),
                            Icon = "update",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 4,
                            QueryParams = "\"{\\u0022sort\\u0022:\\u0022created\\u0022,\\u0022sortDirection\\u0022:\\u0022desc\\u0022}\"",
                            Route = "/menu",
                            Title = "Voci di menu recenti",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2046)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2114),
                            Icon = "dashboard",
                            IsActive = true,
                            MenuGroupId = 2,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/dashboard",
                            Title = "Panoramica",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2114)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2115),
                            Icon = "bar_chart",
                            IsActive = true,
                            MenuGroupId = 2,
                            Order = 2,
                            QueryParams = "\"{}\"",
                            Route = "/stats",
                            Title = "Statistiche",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2115)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2117),
                            Icon = "people",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "",
                            Title = "Utenti",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2117)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2118),
                            Icon = "list",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 1,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/admin/users",
                            Title = "Lista Utenti",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2118)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2120),
                            Icon = "person_add",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 2,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/admin/users/create",
                            Title = "Aggiungi Utente",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2120)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2121),
                            Icon = "admin_panel_settings",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 3,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/admin/security-groups",
                            Title = "Gruppi Sicurezza",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2121)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2122),
                            Icon = "assessment",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/reports",
                            Title = "Reports",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2123)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2124),
                            Icon = "tune",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/config",
                            Title = "Configurazione",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2124)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2125),
                            Icon = "list_alt",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 2,
                            QueryParams = "\"{}\"",
                            Route = "/logs",
                            Title = "Log Sistema",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2125)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2126),
                            Icon = "help",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 3,
                            QueryParams = "\"{}\"",
                            Route = "/support",
                            Title = "Supporto",
                            UpdatedAt = new DateTime(2025, 9, 26, 18, 15, 52, 223, DateTimeKind.Utc).AddTicks(2126)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.GroupPermission", b =>
                {
                    b.HasOne("OIT_Startup_API.Models.Domains.Auth.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OIT_Startup_API.Models.Domains.Auth.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.UserGroup", b =>
                {
                    b.HasOne("OIT_Startup_API.Models.Domains.Auth.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OIT_Startup_API.Models.Domains.Auth.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Menu.MenuItem", b =>
                {
                    b.HasOne("OIT_Startup_API.Models.Domains.Menu.MenuGroup", "MenuGroup")
                        .WithMany("Items")
                        .HasForeignKey("MenuGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OIT_Startup_API.Models.Domains.Menu.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuGroup");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Auth.User", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Menu.MenuGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.Menu.MenuItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
