// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OIT_Startup_API.Data;

#nullable disable

namespace OIT_Startup_API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.MenuGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Order");

                    b.ToTable("MenuGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7861),
                            IsActive = true,
                            Order = 1,
                            Title = "Credenziali",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7862)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7866),
                            IsActive = true,
                            Order = 2,
                            Title = "Dashboard",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7866)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7868),
                            IsActive = true,
                            Order = 3,
                            Title = "Gestione",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7868)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7869),
                            IsActive = true,
                            Order = 4,
                            Title = "Analisi",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7869)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7870),
                            IsActive = true,
                            Order = 5,
                            Title = "Sistema",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MenuGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("QueryParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MenuGroupId");

                    b.HasIndex("Order");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8005),
                            Icon = "list",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/credentials",
                            Title = "Tutte le credenziali",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8005)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8009),
                            Icon = "check_circle",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 2,
                            QueryParams = "\"{\\u0022active\\u0022:true}\"",
                            Route = "/credentials",
                            Title = "Credenziali attive",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8010)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8204),
                            Icon = "error",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 3,
                            QueryParams = "\"{\\u0022expired\\u0022:true}\"",
                            Route = "/credentials",
                            Title = "Credenziali scadute",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8204)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8218),
                            Icon = "update",
                            IsActive = true,
                            MenuGroupId = 1,
                            Order = 4,
                            QueryParams = "\"{\\u0022sort\\u0022:\\u0022created\\u0022,\\u0022sortDirection\\u0022:\\u0022desc\\u0022}\"",
                            Route = "/credentials",
                            Title = "Credenziali recenti",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8219)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8276),
                            Icon = "dashboard",
                            IsActive = true,
                            MenuGroupId = 2,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/dashboard",
                            Title = "Panoramica",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8276)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8278),
                            Icon = "bar_chart",
                            IsActive = true,
                            MenuGroupId = 2,
                            Order = 2,
                            QueryParams = "\"{}\"",
                            Route = "/stats",
                            Title = "Statistiche",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8278)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8279),
                            Icon = "people",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "",
                            Title = "Utenti",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8279)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8281),
                            Icon = "inventory",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 2,
                            QueryParams = "\"{}\"",
                            Route = "",
                            Title = "Prodotti",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8281)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8282),
                            Icon = "list",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 1,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/users/list",
                            Title = "Lista Utenti",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8282)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8284),
                            Icon = "person_add",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 2,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/users/add",
                            Title = "Aggiungi Utente",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8284)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8285),
                            Icon = "admin_panel_settings",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 3,
                            ParentId = 7,
                            QueryParams = "\"{}\"",
                            Route = "/users/roles",
                            Title = "Ruoli & Permessi",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8285)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8287),
                            Icon = "catalog",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 1,
                            ParentId = 8,
                            QueryParams = "\"{}\"",
                            Route = "/products/catalog",
                            Title = "Catalogo",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8287)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8288),
                            Icon = "category",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 2,
                            ParentId = 8,
                            QueryParams = "\"{}\"",
                            Route = "/products/categories",
                            Title = "Categorie",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8288)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8290),
                            Icon = "warehouse",
                            IsActive = true,
                            MenuGroupId = 3,
                            Order = 3,
                            ParentId = 8,
                            QueryParams = "\"{}\"",
                            Route = "/products/inventory",
                            Title = "Inventario",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8290)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8291),
                            Icon = "assessment",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/reports",
                            Title = "Reports",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8291)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8293),
                            Icon = "analytics",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 2,
                            Route = "",
                            Title = "Analytics",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8293)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8294),
                            Icon = "insights",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 1,
                            ParentId = 16,
                            QueryParams = "\"{}\"",
                            Route = "/analytics/overview",
                            Title = "Panoramica",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8294)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8295),
                            Icon = "trending_up",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 2,
                            ParentId = 16,
                            QueryParams = "\"{}\"",
                            Route = "/analytics/sales",
                            Title = "Vendite",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8295)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8297),
                            Icon = "traffic",
                            IsActive = true,
                            MenuGroupId = 4,
                            Order = 3,
                            ParentId = 16,
                            QueryParams = "\"{}\"",
                            Route = "/analytics/traffic",
                            Title = "Traffico",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8297)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8298),
                            Icon = "tune",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 1,
                            QueryParams = "\"{}\"",
                            Route = "/config",
                            Title = "Configurazione",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8298)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8299),
                            Icon = "list_alt",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 2,
                            QueryParams = "\"{}\"",
                            Route = "/logs",
                            Title = "Log Sistema",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8299)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8301),
                            Icon = "help",
                            IsActive = true,
                            MenuGroupId = 5,
                            Order = 3,
                            QueryParams = "\"{}\"",
                            Route = "/support",
                            Title = "Supporto",
                            UpdatedAt = new DateTime(2025, 9, 14, 14, 8, 32, 239, DateTimeKind.Utc).AddTicks(8301)
                        });
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.MenuItem", b =>
                {
                    b.HasOne("OIT_Startup_API.Models.Domains.MenuGroup", "MenuGroup")
                        .WithMany("Items")
                        .HasForeignKey("MenuGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OIT_Startup_API.Models.Domains.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuGroup");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.MenuGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OIT_Startup_API.Models.Domains.MenuItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
